groups:
  - name: host_alerts
    interval: 15s
    rules:
      - alert: HostHighCpu
        expr: (100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
        for: 5m
        labels:
          severity: warning
          component: host
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ $value | humanize }}% on host {{ $labels.instance }} for the last 5 minutes"
